export interface Character {
  slug: string;
  superName: string;
  privateName: string;
  powers: string;
  img: string;
  quote: string;
  category: string;
  color: string;
  status: string;
  team: string;
  description: string;
  allies: string[];
  enemies: string[];
  stats: { strength: number; speed: number; intelligence: number; energy: number; defense: number };
  type: 'hero' | 'villain';
}

function toSlug(name: string) {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

const heroesRaw = [
  { superName: "Paladin", privateName: "Yoav Ramon", powers: "High reflexes", img: "/contents/avatar2024/heroes/paladin-min.webp", quote: "I hold the line.", category: "Combat", color: "#ef4444", status: "Founding Member", team: "Compass Alliance", description: "The steadfast field leader of the Compass Alliance. Yoav's extraordinary reflexes and combat training make him humanity's most reliable defender — calm under fire and always the last to retreat.", allies: ["Voltage", "Lady Astral", "Gigantic", "Comrade", "Tsunami"], enemies: ["Doctor Monstro", "Headmaster Vile"], stats: { strength: 7, speed: 9, intelligence: 8, energy: 5, defense: 8 } },
  { superName: "Lady Astral", privateName: "Princess Mianeska", powers: "Cosmic strength and mist generation", img: "/contents/avatar2024/heroes/ladyAstral-min.webp", quote: "Starlight answers my call.", category: "Cosmic", color: "#a855f7", status: "Founding Member", team: "Compass Alliance", description: "A cosmic princess from the Astral Realm, Mianeska wields starlight itself. After an alien war brought her to Earth, she chose to stay and protect both worlds from the shadows among the stars.", allies: ["Paladin", "Voltage", "Captain Space"], enemies: ["Doctor Monstro"], stats: { strength: 9, speed: 7, intelligence: 7, energy: 9, defense: 7 } },
  { superName: "Voltage", privateName: "Adam Atlas", powers: "Electricity", img: "/contents/avatar2024/heroes/voltage-min.webp", quote: "Hope—now fully charged.", category: "Energy", color: "#facc15", status: "Founding Member", team: "Compass Alliance", description: "The charged heart of the Alliance. Adam carries the weight of electric hope — his mastery of electricity turns every battle into a surge of heroism that lights up the darkest moments.", allies: ["Paladin", "Lady Astral", "Rocket Prime"], enemies: ["Hypno"], stats: { strength: 6, speed: 8, intelligence: 7, energy: 10, defense: 6 } },
  { superName: "Gigantic", privateName: "Michael Hyde", powers: "Super strength (giant build)", img: "/contents/avatar2024/heroes/gigantic-min.webp", quote: "Big frame, bigger heart.", category: "Physical", color: "#f97316", status: "Founding Member", team: "Compass Alliance", description: "Gentle off the field, unstoppable on it. Michael can grow to immense size, becoming a living wall between civilians and catastrophe. His warmth is as legendary as his strength.", allies: ["Paladin", "Comrade", "Size"], enemies: ["Headmaster Vile"], stats: { strength: 10, speed: 4, intelligence: 5, energy: 5, defense: 9 } },
  { superName: "Comrade", privateName: "Sasha Chomesky", powers: "Nuclear blasts", img: "/contents/avatar2024/heroes/comrade-min.webp", quote: "I bear the fallout.", category: "Radiation", color: "#84cc16", status: "Founding Member", team: "Compass Alliance", description: "A product of Cold War-era prime-child experiments, Sasha carries nuclear fire in his veins. He embraces the burden of his radioactive power so that others never have to carry it.", allies: ["Gigantic", "Paladin"], enemies: ["Doctor Monstro"], stats: { strength: 7, speed: 6, intelligence: 6, energy: 10, defense: 7 } },
  { superName: "Tsunami", privateName: "Talia", powers: "Hydrokinesis", img: "/contents/avatar2024/heroes/tsunami-min.webp", quote: "The tide fights with me.", category: "Water", color: "#38bdf8", status: "Founding Member", team: "Compass Alliance", description: "The ocean obeys Talia's will. Whether calming a crisis or unleashing a tidal assault, Tsunami is the Alliance's most versatile force of nature — powerful, precise, and relentless.", allies: ["Paladin", "Lady Astral", "Eastwind"], enemies: ["Hypno"], stats: { strength: 7, speed: 8, intelligence: 7, energy: 8, defense: 7 } },
  { superName: "Dragon Caesar", privateName: "Blake Wu-Chang", powers: "Martial arts master", img: "/contents/avatar2024/heroes/dragonCaesar-min.webp", quote: "Honor strikes faster than flame.", category: "Combat", color: "#ef4444", status: "Active Hero", team: "Compass Alliance", description: "A martial arts prodigy with fists faster than thought. Blake honors a centuries-old fighting tradition while forging his own legend in the modern age of prime-children.", allies: ["Paladin", "Symbol"], enemies: ["Headmaster Vile"], stats: { strength: 8, speed: 9, intelligence: 8, energy: 4, defense: 9 } },
  { superName: "Symbol", privateName: "Nate", powers: "Synthetic man", img: "/contents/avatar2024/heroes/symbol-min.webp", quote: "I am what I choose.", category: "Tech", color: "#60a5fa", status: "Active Hero", team: "Compass Alliance", description: "Neither fully human nor machine, Nate is a synthetic being who chose his own identity. His unique adaptive physiology and sharp mind make him one of the Alliance's most unpredictable assets.", allies: ["Dragon Fighter", "Techno", "Enforcer"], enemies: ["Doctor Monstro"], stats: { strength: 8, speed: 7, intelligence: 9, energy: 7, defense: 8 } },
  { superName: "Size", privateName: "Ben Gordon", powers: "Size changing", img: "/contents/avatar2024/heroes/size-min.webp", quote: "Think big. Grow bigger.", category: "Physical", color: "#f97316", status: "Active Hero", team: "Compass Alliance", description: "Ben can shrink to subatomic scale or grow large enough to stare down skyscrapers. His size-changing power is only surpassed by his oversized courage and determination.", allies: ["Gigantic", "Mariposa"], enemies: ["Headmaster Vile"], stats: { strength: 8, speed: 6, intelligence: 6, energy: 5, defense: 7 } },
  { superName: "Mariposa", privateName: "Nelly Andor", powers: "Magic", img: "/contents/avatar2024/heroes/mariposa-min.webp", quote: "Let courage sprout wings.", category: "Magic", color: "#ec4899", status: "Active Hero", team: "Compass Alliance", description: "A sorceress of butterfly-wing delicacy, Nelly's magic blossoms with breathtaking power in battle. She brings both wonder and devastation to the Compass Alliance, defying every expectation.", allies: ["Size", "Melody"], enemies: ["Hypno"], stats: { strength: 5, speed: 7, intelligence: 8, energy: 9, defense: 6 } },
  { superName: "Enforcer", privateName: "Eli Ramon", powers: "Living shadow / super-detective", img: "/contents/avatar2024/heroes/enforcer-min.webp", quote: "Justice walks in shadow.", category: "Shadow", color: "#6366f1", status: "Active Hero", team: "Solo", description: "Yoav's brother, living in the city's shadows. Eli merges with darkness to become the Alliance's most feared detective — a phantom of justice who never lets criminals rest.", allies: ["Paladin", "Symbol"], enemies: ["Doctor Monstro", "Headmaster Vile"], stats: { strength: 7, speed: 8, intelligence: 10, energy: 6, defense: 7 } },
  { superName: "Melody", privateName: "Shira Ramon", powers: "Super singing", img: "/contents/avatar2024/heroes/melody-min.webp", quote: "Let the truth resonate.", category: "Sonic", color: "#14b8a6", status: "Active Hero", team: "Compass Alliance", description: "Shira's voice resonates at frequencies that can shatter steel or soothe a raging crowd. The youngest Ramon sibling, her sonic powers grow stronger with every note she dares to sing.", allies: ["Mariposa", "Techno"], enemies: ["Hypno"], stats: { strength: 4, speed: 6, intelligence: 8, energy: 8, defense: 5 } },
  { superName: "Techno", privateName: "Alice Carleton", powers: "Technopathy", img: "/contents/avatar2024/heroes/techno-min.webp", quote: "Speak machine. Build tomorrow.", category: "Tech", color: "#60a5fa", status: "Active Hero", team: "Compass Alliance", description: "Alice speaks the language of machines. From hacking satellites to commanding drone swarms, Techno ensures the Alliance is always technologically one step ahead of any threat.", allies: ["Symbol", "Rocket Prime", "Melody"], enemies: ["Doctor Monstro"], stats: { strength: 4, speed: 5, intelligence: 10, energy: 7, defense: 6 } },
  { superName: "Rocket Prime", privateName: "Haim Greenberg", powers: "Giant rocket armor", img: "/contents/avatar2024/heroes/rocketPrime-min.webp", quote: "Launch beyond every limit.", category: "Tech", color: "#60a5fa", status: "Active Hero", team: "Compass Alliance", description: "A genius engineer who built his own power armor from scratch. Haim's rocket suit is more than metal — it embodies decades of dreams turned into the ultimate weapon of sky and space.", allies: ["Techno", "Voltage"], enemies: ["Doctor Monstro"], stats: { strength: 8, speed: 9, intelligence: 8, energy: 9, defense: 9 } },
  { superName: "Captain Space", privateName: "Daniel Ox", powers: "Cosmic omnipotence", img: "/contents/avatar2024/heroes/captainSpace-min.webp", quote: "The cosmos is my canvas.", category: "Cosmic", color: "#a855f7", status: "Active Hero", team: "Solo", description: "Arguably the most powerful being on Earth. Daniel's cosmic omnipotence came at personal cost, but he wields it with quiet wisdom and a sense of purpose that spans galaxies.", allies: ["Lady Astral", "Optimus Quantum"], enemies: ["Doctor Monstro"], stats: { strength: 10, speed: 10, intelligence: 9, energy: 10, defense: 10 } },
  { superName: "Eastwind", privateName: "Unknown", powers: "Aerokinesis", img: "/contents/avatar2024/heroes/eastwind-min.webp", quote: "I ride the unseen wind.", category: "Air", color: "#94a3b8", status: "Active Hero", team: "Solo", description: "A ghost of the east wind — no one knows their true identity. Whenever catastrophe looms, the wind arrives first: fast, decisive, unstoppable, and gone before anyone can say thank you.", allies: ["Tsunami", "Sunshine"], enemies: ["Hypno"], stats: { strength: 5, speed: 10, intelligence: 6, energy: 7, defense: 6 } },
  { superName: "Sunshine", privateName: "Unknown", powers: "Light sword generation", img: "/contents/avatar2024/heroes/sunshine-min.webp", quote: "Light carves a path.", category: "Light", color: "#f59e0b", status: "Active Hero", team: "Solo", description: "Sunshine wields photonic light-swords with graceful, blinding precision. An unknown wanderer with a radiant spirit, they fight evil wherever it hides in the dark.", allies: ["Eastwind", "Optimus Quantum"], enemies: ["Headmaster Vile"], stats: { strength: 6, speed: 7, intelligence: 6, energy: 9, defense: 7 } },
  { superName: "Optimus Quantum", privateName: "Unknown", powers: "Quantum blasts", img: "/contents/avatar2024/heroes/optimusQuantum-min.webp", quote: "Every future chooses hope.", category: "Quantum", color: "#c084fc", status: "Active Hero", team: "Solo", description: "A being of pure quantum potential. Optimus Quantum bends probability itself, firing blasts of focused possibility that no enemy can predict or escape — a living embodiment of uncertain futures.", allies: ["Captain Space", "Sunshine"], enemies: ["Doctor Monstro"], stats: { strength: 7, speed: 7, intelligence: 9, energy: 10, defense: 7 } },
  { superName: "Northlight", privateName: "Noa Feldman", powers: "Light control", img: "/contents/avatar2024/heroes/northlight-min.webp", quote: "Dawn is a decision.", category: "Light", color: "#f59e0b", status: "Active Hero", team: "Compass Alliance", description: "Noa bends photons into blades, shields, and illusions. Northlight specializes in morale warfare, turning despair into momentum during the darkest operations.", allies: ["Paladin", "Lady Astral", "Cheerstar"], enemies: ["General Darkness", "Wizmaster"], stats: { strength: 6, speed: 8, intelligence: 7, energy: 9, defense: 7 } },
  { superName: "Cheerstar", privateName: "Maya Ben-David", powers: "Firework blasts", img: "/contents/avatar2024/heroes/cheerstar-min.webp", quote: "If hope can explode, let it.", category: "Energy", color: "#facc15", status: "Active Hero", team: "Compass Alliance", description: "Maya converts emotional spikes into controlled pyrotechnic bursts. Cheerstar excels in crowd protection missions where precision and spectacle must coexist.", allies: ["Melody", "Northlight", "Tsunami"], enemies: ["Hypno"], stats: { strength: 5, speed: 7, intelligence: 6, energy: 8, defense: 6 } },
  { superName: "Rubberman", privateName: "Ori Halevi", powers: "Elasticity", img: "/contents/avatar2024/heroes/rubber-min.webp", quote: "Bend, never break.", category: "Physical", color: "#f97316", status: "Active Hero", team: "Prime-Children", description: "Ori can stretch, compress, and absorb kinetic impact with near-limitless flexibility. Rubberman is ideal for extraction missions and high-risk rescue zones.", allies: ["Size", "Gigantic"], enemies: ["Mr. Chalk"], stats: { strength: 7, speed: 8, intelligence: 6, energy: 4, defense: 9 } },
  { superName: "Captain Phoenix", privateName: "Eitan Raz", powers: "Pyrokinesis", img: "/contents/avatar2024/heroes/captainPhoenix-min.webp", quote: "From ash, strategy.", category: "Energy", color: "#facc15", status: "Active Hero", team: "Compass Alliance", description: "Eitan commands plasma-grade flame with strict battlefield discipline. Captain Phoenix leads high-temperature containment operations and aerial fire support.", allies: ["Voltage", "Comrade", "Starguard"], enemies: ["Ice Princess"], stats: { strength: 8, speed: 7, intelligence: 7, energy: 9, defense: 7 } },
  { superName: "Starguard", privateName: "Ariel Nave", powers: "Cosmic energy generation", img: "/contents/avatar2024/heroes/starguard-min.webp", quote: "Hold formation. Hold orbit.", category: "Cosmic", color: "#a855f7", status: "Active Hero", team: "Compass Alliance", description: "Ariel channels stellar particles into protective fields and concentrated lances. Starguard acts as a mobile defense platform in off-world engagements.", allies: ["Lady Astral", "Captain Space", "Captain Phoenix"], enemies: ["Doctor Monstro"], stats: { strength: 7, speed: 7, intelligence: 8, energy: 10, defense: 8 } },
  { superName: "Kid Dimension", privateName: "Lior Keshet", powers: "Interdimensional portals", img: "/contents/avatar2024/heroes/kidDimension-min.webp", quote: "Every door is temporary.", category: "Quantum", color: "#c084fc", status: "Active Hero", team: "Prime-Children", description: "Lior opens brief, unstable pathways between nearby dimensions. Kid Dimension is used for tactical repositioning, stealth entry, and emergency extraction.", allies: ["Optimus Quantum", "Techno", "Northlight"], enemies: ["Q", "Headmaster Vile"], stats: { strength: 5, speed: 8, intelligence: 8, energy: 9, defense: 5 } },
  { superName: "Airdance", privateName: "Roni Shalev", powers: "Aerokinesis", img: "/contents/avatar2024/heroes/airdance-min.webp", quote: "Silence has wind.", category: "Air", color: "#94a3b8", status: "Active Hero", team: "Prime-Children", description: "Roni manipulates pressure fronts, turbulence, and micro-currents with dancer-like precision. Airdance controls battlefield spacing better than almost anyone.", allies: ["Eastwind", "Tsunami", "Cheerstar"], enemies: ["Parkour"], stats: { strength: 5, speed: 9, intelligence: 7, energy: 7, defense: 6 } },
  { superName: "Crystallo", privateName: "Gal Tamir", powers: "Crystal form and creation", img: "/contents/avatar2024/heroes/crystallo-min.webp", quote: "Pressure makes structure.", category: "Physical", color: "#f97316", status: "Active Hero", team: "Prime-Children", description: "Gal can generate mineral lattices, form crystal armor, and produce sharp geometric constructs. Crystallo excels in fortification and area denial.", allies: ["Rubberman"], enemies: ["Mudman"], stats: { strength: 8, speed: 5, intelligence: 7, energy: 6, defense: 9 } },
];

const villainsRaw = [
  { superName: "Doctor Monstro", privateName: "Unknown", powers: "Mastermind of science schemes", img: "/contents/avatar2024/villains/DrMonstro.webp", quote: "Progress without ethics is power.", category: "Villain", color: "#dc2626", status: "Villain", team: "The Pyramid", description: "Architect of illegal bio-weapons and alien reverse-engineering programs. Doctor Monstro orchestrates global crises to test his own theories.", allies: ["Headmaster Vile", "Q"], enemies: ["Paladin", "Techno", "Captain Space"], stats: { strength: 4, speed: 5, intelligence: 10, energy: 9, defense: 6 } },
  { superName: "Headmaster Vile", privateName: "Unknown", powers: "Evil principal of Malice School", img: "/contents/avatar2024/villains/headmasterVile.webp", quote: "Talent is nothing without obedience.", category: "Villain", color: "#dc2626", status: "Villain", team: "Malice School", description: "A manipulative educator who recruits unstable Prime-Children into a militarized doctrine of fear and control.", allies: ["Doctor Monstro", "Wizmaster"], enemies: ["Paladin", "Enforcer", "Kid Dimension"], stats: { strength: 5, speed: 5, intelligence: 9, energy: 8, defense: 7 } },
  { superName: "Hypno", privateName: "Unknown", powers: "Can hypnotize everyone", img: "/contents/avatar2024/villains/hypno.webp", quote: "Will is just a fragile habit.", category: "Villain", color: "#dc2626", status: "Villain", team: "Independent", description: "A psychic manipulator who can overwrite short-term decision pathways and turn entire crowds against their own protectors.", allies: ["Q"], enemies: ["Mariposa", "Melody", "Tsunami"], stats: { strength: 3, speed: 5, intelligence: 8, energy: 8, defense: 4 } },
  { superName: "Ice Princess", privateName: "Unknown", powers: "Cryokinesis", img: "/contents/avatar2024/villains/icePrincess.webp", quote: "Cold reveals what heat hides.", category: "Villain", color: "#dc2626", status: "Villain", team: "Independent", description: "An unstable cryokinetic who alternates between rogue survival and uneasy cooperation with hero teams.", allies: ["Q"], enemies: ["Captain Phoenix", "Tsunami"], stats: { strength: 7, speed: 6, intelligence: 6, energy: 9, defense: 7 } },
  { superName: "Q", privateName: "Unknown", powers: "Body reading and mimicry", img: "/contents/avatar2024/villains/q.webp", quote: "Every move has already happened.", category: "Villain", color: "#dc2626", status: "Villain", team: "The Pyramid", description: "A predictive combat savant capable of reading micro-signals and mirroring opponent patterns with terrifying speed.", allies: ["Doctor Monstro", "Hypno"], enemies: ["Dragon Fighter", "Kid Dimension", "Comrade"], stats: { strength: 6, speed: 9, intelligence: 8, energy: 5, defense: 6 } },
  { superName: "General Darkness", privateName: "Unknown", powers: "Consumes dark energy", img: "/contents/avatar2024/villains/generalDarkness.webp", quote: "Light is a temporary condition.", category: "Villain", color: "#dc2626", status: "Villain", team: "The Pyramid", description: "A battlefield commander who weaponizes shadow fields and fear resonance to collapse enemy coordination.", allies: ["Wizmaster", "Headmaster Vile"], enemies: ["Northlight", "Lady Astral", "Sunshine"], stats: { strength: 8, speed: 6, intelligence: 8, energy: 9, defense: 8 } },
  { superName: "Wizmaster", privateName: "Unknown", powers: "Dark magic", img: "/contents/avatar2024/villains/wizmaster.webp", quote: "Rules are for small spells.", category: "Villain", color: "#dc2626", status: "Villain", team: "Occult Cell", description: "An occult tactician specializing in curse lattices, illusion traps, and ritual amplification.", allies: ["General Darkness", "Headmaster Vile"], enemies: ["Mariposa", "Lady Astral", "Northlight"], stats: { strength: 5, speed: 5, intelligence: 9, energy: 10, defense: 6 } },
  { superName: "Killer Volt", privateName: "Unknown", powers: "Electricity", img: "/contents/avatar2024/villains/killerVolt.webp", quote: "Same current, different target.", category: "Villain", color: "#dc2626", status: "Villain", team: "Independent", description: "A rogue electric combatant who mirrors Voltage powers but uses them for sabotage and extortion.", allies: ["Mad Mechanic"], enemies: ["Voltage", "Techno"], stats: { strength: 7, speed: 8, intelligence: 6, energy: 9, defense: 6 } },
  { superName: "Human Rat", privateName: "Unknown", powers: "Rat-like physiology and survival adaptation", img: "/contents/avatar2024/villains/humanRat.webp", quote: "I survive what you ignore.", category: "Villain", color: "#dc2626", status: "Villain", team: "Undercity Ring", description: "An urban predator evolved through toxic exposure and Prime traits, controlling underground black routes.", allies: ["Bushmaster"], enemies: ["Enforcer", "Paladin"], stats: { strength: 6, speed: 7, intelligence: 5, energy: 4, defense: 7 } },
  { superName: "Stickerman", privateName: "Unknown", powers: "Explosive stickers", img: "/contents/avatar2024/villains/stickerman.webp", quote: "Containment is a political word.", category: "Villain", color: "#dc2626", status: "Villain", team: "Independent", description: "A living atomic source capable of wide-area fallout pulses and thermal collapse events.", allies: ["Doctor Monstro"], enemies: ["Comrade", "Captain Phoenix", "Starguard"], stats: { strength: 8, speed: 4, intelligence: 7, energy: 10, defense: 8 } },
];

export const heroes: Character[] = heroesRaw.map(h => ({ ...h, slug: toSlug(h.superName), type: 'hero' as const }));
export const villains: Character[] = villainsRaw.map(v => ({ ...v, slug: toSlug(v.superName), type: 'villain' as const }));
export const allCharacters: Character[] = [...heroes, ...villains];

export function getCharacterBySlug(slug: string): Character | undefined {
  return allCharacters.find(c => c.slug === slug);
}
